import { useEffect, useMemo, useRef, useState, type CSSProperties, type ChangeEvent } from "react";
import { Link } from "wouter";
import { ArrowDown, ArrowUp, Download, Eye, Facebook, FileUp, History, Instagram, Loader2, MapPin, Palette, Plus, Sparkles, Trash2, Upload } from "lucide-react";
import { useAuth } from "@/_core/hooks/useAuth";
import { OwnerLoginButton } from "@/components/OwnerLoginModal";
import { OWNER_DASHBOARD_PATH } from "@/const";
import { trpc } from "@/lib/trpc";
import { buildCustomFontFace } from "@/fontFace";
import { getFontPreviewFamily, resetFontChoice } from "@/fontSettings";
import { memoryFeatureGuide } from "@/memoryFeatureGuide";
import { getVisualTheme, visualThemes, type VisualThemeId } from "@/themeGallery";

type TimelineEntry = { id: string; title: string; date: string; description: string };
type PlaceEntry = { id: string; name: string; mapUrl: string };
type StoryNote = { id: string; title: string; body: string; publishAt: string };
type FeatureState = { songLabel: string; welcomeTitle: string; welcomeMessage: string; fontFamily: "gaegu" | "serif" | "sans"; customFontUrl: string; customFontName: string; backgroundStyle: "soft" | "sunset" | "night" | "paper"; themeMode: "light" | "night" | "auto"; visualTheme: VisualThemeId; questionLetterEnabled: boolean; questionLetterTitle: string; questionLetterPrompt: string; questionLetterRecipient: string; hideVideos: boolean; hideGallery: boolean; hideMessage: boolean; surpriseTitle: string; surpriseMessage: string; surpriseAt: string; timeline: TimelineEntry[]; places: PlaceEntry[]; notes: StoryNote[]; ownerNote: string };
const defaultFeatures = (): FeatureState => ({ songLabel: "Our Song ❤️", welcomeTitle: "", welcomeMessage: "", fontFamily: "gaegu", customFontUrl: "", customFontName: "", backgroundStyle: "soft", themeMode: "light", visualTheme: "soft-love", questionLetterEnabled: false, questionLetterTitle: "คำถามถึงเธอ", questionLetterPrompt: "วันนี้อยากบอกอะไรกับเราไหม?", questionLetterRecipient: "", hideVideos: false, hideGallery: false, hideMessage: false, surpriseTitle: "", surpriseMessage: "", surpriseAt: "", timeline: [], places: [], notes: [], ownerNote: "" });
const makeId = () => (globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(36).slice(2)}`);
function readAsDataUrl(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error("ไม่สามารถอ่านไฟล์ได้")); reader.readAsDataURL(file); }); }
const MAX_INLINE_UPLOAD_BYTES = 2_500_000;
const uploadLimitMessage = "ไฟล์เกิน 2.5MB จึงอัปโหลดผ่าน Vercel ไม่ได้ กรุณาเลือกไฟล์ขนาดเล็กลง";
function friendlyUploadError(error: unknown) { const message = error instanceof Error ? error.message : "อัปโหลดไม่สำเร็จ"; return /request entity too large|unexpected token ['\"]?r/i.test(message) ? uploadLimitMessage : message; }
async function prepareImageForUpload(file: File): Promise<File> {
  if (file.size <= MAX_INLINE_UPLOAD_BYTES) return file;
  if (!file.type.startsWith("image/")) throw new Error(uploadLimitMessage);
  try {
    const bitmap = await createImageBitmap(file);
    const maxSide = 1600;
    const scale = Math.min(1, maxSide / Math.max(bitmap.width, bitmap.height));
    const canvas = document.createElement("canvas");
    canvas.width = Math.max(1, Math.round(bitmap.width * scale));
    canvas.height = Math.max(1, Math.round(bitmap.height * scale));
    canvas.getContext("2d")?.drawImage(bitmap, 0, 0, canvas.width, canvas.height);
    bitmap.close();
    const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, "image/jpeg", 0.82));
    if (!blob || blob.size > MAX_INLINE_UPLOAD_BYTES) throw new Error(uploadLimitMessage);
    return new File([blob], `${file.name.replace(/\.[^.]+$/, "") || "photo"}.jpg`, { type: "image/jpeg" });
  } catch (error) {
    throw error instanceof Error ? error : new Error(uploadLimitMessage);
  }
}

export default function Settings({ slug }: { slug: string }) {
  const utils = trpc.useUtils(); const { isAuthenticated, loading } = useAuth();
  const adminQuery = trpc.site.admin.get.useQuery({ slug }, { enabled: isAuthenticated });
  const [facebookUrl, setFacebookUrl] = useState(""); const [instagramUrl, setInstagramUrl] = useState(""); const [musicUrl, setMusicUrl] = useState(""); const [themeColor, setThemeColor] = useState("#ec4899"); const [features, setFeatures] = useState<FeatureState>(defaultFeatures); const [pin, setPin] = useState(""); const [uploading, setUploading] = useState(false); const [emailTo, setEmailTo] = useState(""); const [emailSubject, setEmailSubject] = useState(""); const [emailMessage, setEmailMessage] = useState("");
  const importRef = useRef<HTMLInputElement>(null);
  const [status, setStatus] = useState<{ tone: "success" | "error" | "info"; message: string } | null>(null);
  const invalidate = () => { void utils.site.admin.get.invalidate({ slug }); void utils.site.private.get.invalidate({ slug }); };
  const saveMutation = trpc.site.admin.saveSettings.useMutation({ onSuccess: () => { invalidate(); setStatus({ tone: "success", message: "บันทึกการตั้งค่าแล้ว" }); }, onError: (error) => setStatus({ tone: "error", message: `บันทึกไม่สำเร็จ: ${error.message}` }) });
  const uploadMutation = trpc.site.admin.uploadMedia.useMutation({ onSuccess: (asset) => { if (asset.kind === "audio") setMusicUrl(asset.url); invalidate(); }, onError: (error) => setStatus({ tone: "error", message: `อัปโหลดไม่สำเร็จ: ${friendlyUploadError(error)}` }) });
  const uploadFontMutation = trpc.site.admin.uploadFont.useMutation({ onSuccess: (font) => { update("customFontUrl", font.url); update("customFontName", font.name); invalidate(); setStatus({ tone: "success", message: "อัปโหลดฟอนต์แล้ว และนำไปใช้กับหน้าบ้านทันที" }); }, onError: (error) => setStatus({ tone: "error", message: `อัปโหลดฟอนต์ไม่สำเร็จ: ${error.message}` }) });
  const removeMutation = trpc.site.admin.removeMedia.useMutation({ onSuccess: () => { invalidate(); setStatus({ tone: "success", message: "ลบไฟล์แล้ว" }); }, onError: (error) => setStatus({ tone: "error", message: `ลบไฟล์ไม่สำเร็จ: ${error.message}` }) });
  const reorderMutation = trpc.site.admin.reorderMedia.useMutation({ onSuccess: invalidate, onError: (error) => setStatus({ tone: "error", message: `จัดเรียงไม่สำเร็จ: ${error.message}` }) });
  const sendEmailMutation = trpc.site.admin.sendEmail.useMutation({ onSuccess: () => { setEmailMessage(""); setStatus({ tone: "success", message: "ส่งอีเมลเรียบร้อยแล้ว" }); }, onError: (error) => setStatus({ tone: "error", message: `ส่งอีเมลไม่สำเร็จ: ${error.message}` }) });
  useEffect(() => { const s = adminQuery.data?.settings; if (s) { setFacebookUrl(s.facebookUrl ?? ""); setInstagramUrl(s.instagramUrl ?? ""); setMusicUrl(s.musicUrl ?? ""); setThemeColor(s.themeColor ?? "#ec4899"); setFeatures({ ...defaultFeatures(), ...(s.features ?? {}) }); } }, [adminQuery.data?.settings]);
  const assets = adminQuery.data?.assets ?? []; const videos = useMemo(() => assets.filter((a) => a.kind === "video"), [assets]); const images = useMemo(() => assets.filter((a) => a.kind === "image"), [assets]); const songs = useMemo(() => assets.filter((a) => a.kind === "audio"), [assets]);
  const update = <K extends keyof FeatureState>(key: K, value: FeatureState[K]) => setFeatures((old) => ({ ...old, [key]: value }));
  const customFontFace = buildCustomFontFace(features.customFontUrl);
  const fontPreviewStyle: CSSProperties = { fontFamily: getFontPreviewFamily(features) };
  const resetFont = () => { setFeatures((old) => resetFontChoice(old)); setStatus({ tone: "info", message: "คืนค่าเป็นฟอนต์ลายมือมาตรฐานแล้ว — กดบันทึกทั้งหมดเพื่อนำไปใช้" }); };
  const applyVisualTheme = (id: VisualThemeId) => { const theme = getVisualTheme(id); setThemeColor(theme.themeColor); setFeatures((old) => ({ ...old, visualTheme: theme.id, backgroundStyle: theme.backgroundStyle, themeMode: theme.themeMode, fontFamily: theme.fontFamily })); setStatus({ tone: "info", message: `เลือกธีม ${theme.name} แล้ว — กดบันทึกทั้งหมดเพื่อนำไปใช้` }); };
  const updateList = <K extends "timeline" | "places" | "notes">(key: K, index: number, value: FeatureState[K][number]) => setFeatures((old) => ({ ...old, [key]: old[key].map((item, i) => i === index ? value : item) }));
  const removeList = <K extends "timeline" | "places" | "notes">(key: K, index: number) => setFeatures((old) => ({ ...old, [key]: old[key].filter((_, i) => i !== index) }));
  const uploadFiles = async (kind: "image" | "video" | "audio", files: File[]) => { if (!files.length) return; if (kind === "video" && videos.length + files.length > 4) return setStatus({ tone: "error", message: "อัปโหลดวิดีโอได้สูงสุด 4 ไฟล์" }); setUploading(true); try { for (const originalFile of files) { const file = kind === "image" ? await prepareImageForUpload(originalFile) : originalFile; if (file.size > MAX_INLINE_UPLOAD_BYTES) throw new Error(uploadLimitMessage); await uploadMutation.mutateAsync({ slug, kind, fileName: file.name, dataUrl: await readAsDataUrl(file) }); } setStatus({ tone: "success", message: "อัปโหลดเรียบร้อยแล้ว" }); } finally { setUploading(false); } };
  const onFiles = (kind: "image" | "video" | "audio") => async (event: ChangeEvent<HTMLInputElement>) => { try { await uploadFiles(kind, Array.from(event.target.files ?? [])); } catch (error) { setStatus({ tone: "error", message: friendlyUploadError(error) }); } finally { event.target.value = ""; } };
  const onFontFile = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; try { if (!file) return; if (file.size > MAX_INLINE_UPLOAD_BYTES) throw new Error(uploadLimitMessage); setUploading(true); await uploadFontMutation.mutateAsync({ slug, fileName: file.name, dataUrl: await readAsDataUrl(file) }); } catch (error) { setStatus({ tone: "error", message: friendlyUploadError(error) }); } finally { setUploading(false); event.target.value = ""; } };
  const save = () => { setStatus({ tone: "info", message: "กำลังบันทึกการตั้งค่า…" }); saveMutation.mutate({ slug, facebookUrl: facebookUrl.trim(), instagramUrl: instagramUrl.trim(), musicUrl: musicUrl.trim(), themeColor, pin: pin || undefined, features }); };
  const sendEmail = () => { if (!window.confirm(`ยืนยันส่งอีเมลไปที่ ${emailTo.trim()}?`)) return; setStatus({ tone: "info", message: "กำลังส่งอีเมล…" }); sendEmailMutation.mutate({ slug, to: emailTo.trim(), subject: emailSubject.trim(), message: emailMessage.trim() }); };
  const moveMedia = async (items: Array<{ id: number; sortOrder: number }>, index: number, direction: number) => { const target = items[index + direction]; const current = items[index]; if (!target || !current) return; await reorderMutation.mutateAsync({ slug, id: current.id, sortOrder: target.sortOrder }); await reorderMutation.mutateAsync({ slug, id: target.id, sortOrder: current.sortOrder }); };
  const exportSettings = () => { const file = new Blob([JSON.stringify({ version: 1, exportedAt: new Date().toISOString(), facebookUrl, instagramUrl, musicUrl, themeColor, features }, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(file); const link = document.createElement("a"); link.href = url; link.download = `${slug}-settings-backup.json`; link.click(); URL.revokeObjectURL(url); };
  const importSettings = async (file?: File) => { if (!file) return; try { const backup = JSON.parse(await file.text()); if (!backup.features || typeof backup.themeColor !== "string") throw new Error("ไฟล์สำรองไม่ถูกต้อง"); setFacebookUrl(String(backup.facebookUrl ?? "")); setInstagramUrl(String(backup.instagramUrl ?? "")); setMusicUrl(String(backup.musicUrl ?? "")); setThemeColor(backup.themeColor); setFeatures({ ...defaultFeatures(), ...backup.features }); setStatus({ tone: "success", message: "โหลดไฟล์สำรองแล้ว — กดบันทึกทั้งหมดเพื่อยืนยัน" }); } catch { setStatus({ tone: "error", message: "ไม่สามารถอ่านไฟล์สำรองนี้ได้" }); } };
  if (loading || (isAuthenticated && adminQuery.isLoading)) return <div className="legacy-admin-screen"><div className="legacy-admin-box text-center"><Loader2 className="mx-auto animate-spin text-pink-500" /></div></div>;
  if (!isAuthenticated) return <div className="legacy-admin-screen"><div className="legacy-admin-box text-center"><h3>เว็บไซต์ส่วนตัว</h3><p className="legacy-admin-note">เข้าสู่ระบบเจ้าของเว็บไซต์ก่อนเพื่อจัดการข้อมูล</p><OwnerLoginButton className="legacy-save-btn mt-5">Sign in</OwnerLoginButton></div></div>;
  if (adminQuery.error || !adminQuery.data) return <div className="legacy-admin-screen"><div className="legacy-admin-box text-center"><h3>ไม่พบเว็บไซต์นี้</h3><Link className="legacy-close-btn mt-4 inline-block" href={OWNER_DASHBOARD_PATH}>กลับหลังบ้าน</Link></div></div>;
  return <div className="legacy-admin-screen"><section className="legacy-admin-box !max-w-xl"><h3>{adminQuery.data.site.title}</h3><div className="legacy-admin-stack">
	    {status && <p className={`legacy-status legacy-status-${status.tone}`} role="status">{status.message}</p>}
	    {customFontFace && <style data-settings-custom-font>{customFontFace}</style>}
	    <div className="legacy-basic-card legacy-font-preview-card"><h4>ตัวอย่างฟอนต์ก่อนใช้จริง</h4><p className="legacy-font-preview" style={fontPreviewStyle}>รักเจนนะ 123 · LoveOffice memories</p><p className="legacy-admin-note">{features.customFontName ? `ฟอนต์ส่วนตัว: ${features.customFontName}` : features.fontFamily === "gaegu" ? "ฟอนต์ลายมือมาตรฐาน" : `ฟอนต์มาตรฐาน: ${features.fontFamily}`}</p>{features.customFontUrl && <button type="button" className="legacy-font-reset-btn" onClick={resetFont}>คืนค่าเริ่มต้น</button>}</div>
	    <div className="legacy-basic-card legacy-memory-hub"><h4>ฟีเจอร์ความทรงจำใหม่</h4><p className="legacy-admin-note">ตั้งค่าได้จากการ์ดด้านล่าง แล้วกดบันทึกทั้งหมดเพื่อนำไปใช้บนหน้าบ้าน</p><div className="legacy-memory-hub-grid">{memoryFeatureGuide.map((item) => <div key={item.title}><strong>{item.icon} {item.title}</strong><span>{item.description}</span></div>)}</div></div>
	    <div className="legacy-basic-card legacy-theme-gallery"><h4>Theme Gallery — เลือกหน้าตาเว็บไซต์</h4><p className="legacy-admin-note">เลือกได้ 6 แบบ ข้อมูลรูป เพลง วิดีโอ และความทรงจำจะอยู่ครบเหมือนเดิม</p><div className="legacy-theme-gallery-grid">{visualThemes.map((theme) => <button key={theme.id} type="button" onClick={() => applyVisualTheme(theme.id)} className={`legacy-theme-tile legacy-theme-tile-${theme.id} ${features.visualTheme === theme.id ? "is-selected" : ""}`}><span className="legacy-theme-tile-preview" /><strong>{theme.name}</strong><small>{theme.description}</small>{features.visualTheme === theme.id && <em>กำลังเลือกอยู่</em>}</button>)}</div></div>
	    <div className="legacy-basic-card legacy-email-card"><h4>ส่งข้อความทางอีเมล</h4><p className="legacy-admin-note">ส่งผ่าน LoveOffice จากหลังบ้านโดยตรง ระบบจะให้ยืนยันอีกครั้งก่อนส่งจริง</p><input type="email" className="legacy-file-input" value={emailTo} onChange={(e) => setEmailTo(e.target.value)} placeholder="อีเมลผู้รับ" /><input className="legacy-file-input" value={emailSubject} onChange={(e) => setEmailSubject(e.target.value)} placeholder="หัวข้ออีเมล" /><textarea className="legacy-file-input" value={emailMessage} onChange={(e) => setEmailMessage(e.target.value)} placeholder="ข้อความถึงคนพิเศษ" rows={5} /><button type="button" className="legacy-save-btn" disabled={sendEmailMutation.isPending || !emailTo.trim() || !emailSubject.trim() || !emailMessage.trim()} onClick={sendEmail}>{sendEmailMutation.isPending ? <Loader2 size={16} className="animate-spin" /> : "✉️"}ส่งอีเมล</button><p className="legacy-admin-note">หากยังไม่ได้ยืนยันโดเมนผู้ส่งใน Resend ระบบอาจจำกัดการส่งถึงอีเมลของบัญชี Resend ก่อน</p></div>
	    <div className="legacy-basic-card legacy-question-settings"><h4>จดหมายคำถามและคำตอบกลับ</h4><p className="legacy-admin-note">เปิดจดหมายนี้บนหน้าบ้านเพื่อให้คนพิเศษตอบคำถาม แล้วส่งคำตอบเข้าอีเมลที่กำหนด</p><label className="flex items-center gap-2"><input type="checkbox" checked={features.questionLetterEnabled} onChange={(e) => update("questionLetterEnabled", e.target.checked)} />เปิดจดหมายคำถามบนหน้าบ้าน</label><input className="legacy-file-input" value={features.questionLetterTitle} onChange={(e) => update("questionLetterTitle", e.target.value)} placeholder="หัวข้อจดหมาย" /><textarea className="legacy-file-input" value={features.questionLetterPrompt} onChange={(e) => update("questionLetterPrompt", e.target.value)} placeholder="คำถามที่อยากถาม" rows={3} /><input type="email" className="legacy-file-input" value={features.questionLetterRecipient} onChange={(e) => update("questionLetterRecipient", e.target.value)} placeholder="อีเมลรับคำตอบ" /><p className="legacy-admin-note">กดบันทึกทั้งหมดหลังแก้ไข และอีเมลนี้จะไม่แสดงบนหน้าบ้าน</p></div>
    <div className="legacy-basic-card"><h4>สื่อและลำดับแสดงผล</h4><label>วิดีโอ (สูงสุด 4 ช่อง)</label>{Array.from({ length: 4 }, (_, i) => { const asset = videos[i]; return <div className="legacy-upload-row" key={i}>{asset ? <><span className="truncate">{i + 1}. {asset.originalName}</span><button type="button" disabled={i === 0 || reorderMutation.isPending} onClick={() => void moveMedia(videos, i, -1)}><ArrowUp size={14} /></button><button type="button" disabled={i === videos.length - 1 || reorderMutation.isPending} onClick={() => void moveMedia(videos, i, 1)}><ArrowDown size={14} /></button><button type="button" onClick={() => removeMutation.mutate({ slug, id: asset.id })}><Trash2 size={15} /></button></> : <input type="file" accept="video/*" className="legacy-file-input" disabled={uploading} onChange={onFiles("video")} />}</div>; })}<label className="mt-3">แกลเลอรี่ภาพ</label><input type="file" accept="image/*" multiple className="legacy-file-input" disabled={uploading} onChange={onFiles("image")} />{images.map((a, i) => <div className="legacy-upload-row" key={a.id}><span>{i + 1}. {a.originalName}</span><button type="button" disabled={i === 0 || reorderMutation.isPending} onClick={() => void moveMedia(images, i, -1)}><ArrowUp size={14} /></button><button type="button" disabled={i === images.length - 1 || reorderMutation.isPending} onClick={() => void moveMedia(images, i, 1)}><ArrowDown size={14} /></button><button type="button" onClick={() => removeMutation.mutate({ slug, id: a.id })}><Trash2 size={15} /></button></div>)}<label className="mt-3">อัปโหลดเพลง (ไฟล์ไม่เกิน 2.5MB)</label><input type="file" accept="audio/mpeg,.mp3,audio/*" className="legacy-file-input" disabled={uploading} onChange={onFiles("audio")} /><p className="legacy-admin-note">เลือกไฟล์เพลงจากเครื่อง แล้วกดบันทึกทั้งหมดหลังอัปโหลดเสร็จ</p>{songs.map((a) => <div className="legacy-upload-row" key={a.id}><span>{a.originalName}</span><button type="button" onClick={() => removeMutation.mutate({ slug, id: a.id })}><Trash2 size={15} /></button></div>)}</div>
    <div className="legacy-basic-card"><h4 className="flex items-center gap-2"><Palette size={14} />ธีมและข้อความเปิดเว็บ</h4><label>ธีมสำเร็จรูป<select className="legacy-file-input" defaultValue="" onChange={(e) => { const preset = e.target.value; if (preset === "pink") { setThemeColor("#ec4899"); update("backgroundStyle", "soft"); } if (preset === "sunset") { setThemeColor("#f97316"); update("backgroundStyle", "sunset"); } if (preset === "sky") { setThemeColor("#2563eb"); update("backgroundStyle", "paper"); } if (preset === "night") { setThemeColor("#a855f7"); update("backgroundStyle", "night"); update("themeMode", "night"); } }}><option value="">เลือกเอง</option><option value="pink">Pink Love</option><option value="sunset">Sunset</option><option value="sky">Blue Sky</option><option value="night">Night Sky</option></select></label><label>สีธีม (กรอกได้เป็น #RRGGBB)</label><div className="flex gap-3"><input type="color" value={/^#[0-9a-fA-F]{6}$/.test(themeColor) ? themeColor : "#ec4899"} onChange={(e) => setThemeColor(e.target.value)} /><input className="legacy-file-input !mb-0" value={themeColor} onChange={(e) => setThemeColor(e.target.value.trim())} placeholder="#EC4899" /></div><label>ข้อความบนปุ่มเพลง</label><input className="legacy-file-input" value={features.songLabel} onChange={(e) => update("songLabel", e.target.value)} /><label>หัวข้อต้อนรับ</label><input className="legacy-file-input" value={features.welcomeTitle} onChange={(e) => update("welcomeTitle", e.target.value)} /><label>ข้อความต้อนรับ</label><textarea className="legacy-file-input" value={features.welcomeMessage} onChange={(e) => update("welcomeMessage", e.target.value)} /><div className="legacy-admin-grid"><label>ฟอนต์<select className="legacy-file-input" value={features.fontFamily} onChange={(e) => update("fontFamily", e.target.value as FeatureState["fontFamily"])}><option value="gaegu">ลายมือ</option><option value="serif">Serif</option><option value="sans">Sans</option></select></label><label>ฟอนต์ส่วนตัว (WOFF2/TTF/OTF)<input type="file" accept=".woff,.woff2,.ttf,.otf,font/*" className="legacy-file-input" disabled={uploading} onChange={(e) => void onFontFile(e)} />{features.customFontName && <span className="legacy-admin-note">กำลังใช้: {features.customFontName}</span>}</label><label>พื้นหลัง<select className="legacy-file-input" value={features.backgroundStyle} onChange={(e) => update("backgroundStyle", e.target.value as FeatureState["backgroundStyle"])}><option value="soft">Soft</option><option value="sunset">Sunset</option><option value="night">Night</option><option value="paper">Paper</option></select></label></div><label>โหมดสี<select className="legacy-file-input" value={features.themeMode} onChange={(e) => update("themeMode", e.target.value as FeatureState["themeMode"])}><option value="light">สว่าง</option><option value="night">กลางคืน</option><option value="auto">อัตโนมัติ</option></select></label></div>
    <div className="legacy-basic-card"><h4>ส่วนที่จะแสดง</h4>{([ ["hideVideos", "ซ่อนวิดีโอ"], ["hideGallery", "ซ่อนแกลเลอรี่"], ["hideMessage", "ซ่อนข้อความหลัก"] ] as const).map(([key, label]) => <label key={key} className="flex items-center gap-2"><input type="checkbox" checked={!features[key]} onChange={(e) => update(key, !e.target.checked)} />แสดง{label.replace("ซ่อน", "")}</label>)}</div>
    <div className="legacy-basic-card"><h4 className="flex items-center gap-2"><Sparkles size={14} />โหมดเซอร์ไพรส์</h4><input className="legacy-file-input" placeholder="หัวข้อเซอร์ไพรส์" value={features.surpriseTitle} onChange={(e) => update("surpriseTitle", e.target.value)} /><textarea className="legacy-file-input" placeholder="ข้อความเซอร์ไพรส์" value={features.surpriseMessage} onChange={(e) => update("surpriseMessage", e.target.value)} /><label>เวลาเผยแพร่<input type="datetime-local" className="legacy-file-input" value={features.surpriseAt} onChange={(e) => update("surpriseAt", e.target.value)} /></label></div>
    <div className="legacy-basic-card"><h4>ไทม์ไลน์ความทรงจำ</h4>{features.timeline.map((item, i) => <div className="legacy-input-stack mb-3" key={item.id}><input className="legacy-file-input" placeholder="ชื่อเหตุการณ์" value={item.title} onChange={(e) => updateList("timeline", i, { ...item, title: e.target.value })} /><input type="date" className="legacy-file-input" value={item.date} onChange={(e) => updateList("timeline", i, { ...item, date: e.target.value })} /><textarea className="legacy-file-input" placeholder="รายละเอียด" value={item.description} onChange={(e) => updateList("timeline", i, { ...item, description: e.target.value })} /><button type="button" onClick={() => removeList("timeline", i)} className="text-rose-600">ลบเหตุการณ์</button></div>)}<button type="button" className="legacy-close-btn" onClick={() => update("timeline", [...features.timeline, { id: makeId(), title: "", date: "", description: "" }])}><Plus size={14} />เพิ่มเหตุการณ์</button></div>
    <div className="legacy-basic-card"><h4 className="flex items-center gap-2"><MapPin size={14} />สถานที่พิเศษ</h4>{features.places.map((item, i) => <div className="legacy-input-stack mb-3" key={item.id}><input className="legacy-file-input" placeholder="ชื่อสถานที่" value={item.name} onChange={(e) => updateList("places", i, { ...item, name: e.target.value })} /><input className="legacy-file-input" placeholder="https://maps.google.com/..." value={item.mapUrl} onChange={(e) => updateList("places", i, { ...item, mapUrl: e.target.value })} /><button type="button" onClick={() => removeList("places", i)} className="text-rose-600">ลบสถานที่</button></div>)}<button type="button" className="legacy-close-btn" onClick={() => update("places", [...features.places, { id: makeId(), name: "", mapUrl: "" }])}><Plus size={14} />เพิ่มสถานที่</button></div>
    <div className="legacy-basic-card"><h4>สมุดข้อความ</h4>{features.notes.map((item, i) => <div className="legacy-input-stack mb-3" key={item.id}><input className="legacy-file-input" placeholder="หัวข้อ" value={item.title} onChange={(e) => updateList("notes", i, { ...item, title: e.target.value })} /><textarea className="legacy-file-input" placeholder="ข้อความ" value={item.body} onChange={(e) => updateList("notes", i, { ...item, body: e.target.value })} /><label>เผยแพร่เมื่อ<input type="datetime-local" className="legacy-file-input" value={item.publishAt} onChange={(e) => updateList("notes", i, { ...item, publishAt: e.target.value })} /></label><button type="button" onClick={() => removeList("notes", i)} className="text-rose-600">ลบข้อความ</button></div>)}<button type="button" className="legacy-close-btn" onClick={() => update("notes", [...features.notes, { id: makeId(), title: "", body: "", publishAt: "" }])}><Plus size={14} />เพิ่มข้อความ</button><label className="mt-3">โน้ตส่วนตัว (ไม่แสดงหน้าบ้าน)<textarea className="legacy-file-input" value={features.ownerNote} onChange={(e) => update("ownerNote", e.target.value)} /></label></div>
    <div className="legacy-basic-card"><h4>ช่องทางติดต่อและความเป็นส่วนตัว</h4><label className="flex items-center gap-2"><Facebook size={13} />Facebook URL</label><input type="url" className="legacy-file-input" value={facebookUrl} onChange={(e) => setFacebookUrl(e.target.value)} placeholder="https://facebook.com/..." /><label className="flex items-center gap-2"><Instagram size={13} />Instagram URL</label><input type="url" className="legacy-file-input" value={instagramUrl} onChange={(e) => setInstagramUrl(e.target.value)} placeholder="https://instagram.com/..." /><label>เปลี่ยน PIN ของเว็บไซต์ (4 หลัก)<input className="legacy-file-input" inputMode="numeric" maxLength={4} value={pin} placeholder="เว้นว่างเพื่อใช้ PIN เดิม" onChange={(e) => setPin(e.target.value.replace(/\D/g, "").slice(0, 4))} /></label></div>
    <div className="legacy-basic-card"><h4 className="flex items-center gap-2"><History size={14} />สำรอง ตัวอย่าง และสถิติ</h4><p className="legacy-admin-note text-left">เปิดหน้าบ้านแล้ว {adminQuery.data.viewCount} ครั้ง · ใช้สื่อ {(adminQuery.data.storageBytes / 1_048_576).toFixed(2)} MB</p><div className="legacy-admin-actions"><button type="button" className="legacy-close-btn" onClick={exportSettings}><Download size={14} />สำรอง</button><button type="button" className="legacy-close-btn" onClick={() => importRef.current?.click()}><FileUp size={14} />กู้คืน</button><a className="legacy-close-btn" href={`/site/${slug}`} target="_blank" rel="noreferrer"><Eye size={14} />ตัวอย่าง</a></div><input ref={importRef} type="file" accept="application/json" className="hidden" onChange={(e) => { void importSettings(e.target.files?.[0]); e.target.value = ""; }} /><p className="legacy-admin-note">สำรองเฉพาะการตั้งค่า ไม่รวมไฟล์สื่อ</p>{(adminQuery.data.settings.revisionLog ?? []).slice(0, 5).map((item) => <p className="legacy-admin-note text-left" key={item.at}>• {new Date(item.at).toLocaleString("th-TH")}: {item.label}</p>)}</div>
    <div className="legacy-admin-actions"><button className="legacy-save-btn" type="button" onClick={save} disabled={saveMutation.isPending || uploading}>{saveMutation.isPending || uploading ? <Loader2 size={16} className="animate-spin" /> : <Upload size={16} />}บันทึกทั้งหมด</button><Link className="legacy-close-btn" href={`/site/${slug}`}>ดูเว็บไซต์</Link></div><Link className="legacy-close-btn text-center" href={OWNER_DASHBOARD_PATH}>กลับหลังบ้าน</Link>
  </div></section></div>;
}
